# Generated by Django 3.1.2 on 2020-12-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20201217_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, max_length=1023, null=True, verbose_name='Описание пользователя'),
        ),
    ]
